name: tests
on:
  push:
jobs:
  tests:
    name: java-${{ matrix.java }} unit tests
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    strategy:
      matrix:
        java: [17, 21, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.docker
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - run: command -v docker >/dev/null 2>&1 || { echo >&2 "Docker is required but not installed.  Aborting."; exit 1; }
      - run: cd $GITHUB_WORKSPACE ; ./mvnw clean ; ./mvnw
