name: updates
on:
  push:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
jobs:
  check-maven-updates:
    name: check maven updates
    #if: startsWith(github.event.inputs.trigger, 'm') || startsWith(github.event.inputs.trigger, 'M')
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    strategy:
      matrix:
        java: [17, 21, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.node
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-parent-updates
      - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-plugin-updates
      - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-property-updates
